### ISSUE TITLE
can we add "battery health" in the extension

### ISSUE THREAD

**Issue by jatindotdev** [o1y/raycast-battery-health-check#1]
hey i find your extension pretty helpfully was looking for one like that.

just wanted to ask if we can have remaining battery health in that.

thanks!

**Comment by o1y** [comment]
Hey @codewjatin,

thanks again! I've merged your PR #2.

I will merge the changes very soon to the raycast extension repo so you will be able to see the changes. :)

Thanks!
Oliver
